### ISSUE TITLE
Object Export Failed

### ISSUE THREAD

**Issue by blumenbart** [Takanu/GEX#37] opened 2022-09-05 13:50 UTC
Hi, I really love your tool. It's a huge time saver, and I use it almost every day.
I recently updated Blender to 3.2.2. I get this error if I try to export objects. (Collections work)

![grafik](https://user-images.githubusercontent.com/9818227/188464222-cdcec387-696b-41eb-a577-bc0755a1222e.png)

I tried every different export setting, but this happens all the time. In 3.1, everything worked well.

Would really appreciate it if you could help me out, as I don't want to go back to 3.1 :)

**Comment by Takanu** [comment] 2022-09-07 10:34
Thanks for submitting this, I haven't come across this before though it may be because I'm currently using 3.3.  I will investigate it when I have time 👌

**Comment by Takanu** [comment] 2022-09-07 16:29
I think I fixed it, can you check this version and see if the problem is fixed? 

[Capsule-master.zip](https://github.com/Takanu/Capsule/files/9508032/Capsule-master.zip)

**Comment by blumenbart** [comment] 2022-09-07 20:00
Hey wow, thank you <3 - Did a short test and it seems to work :)

**Comment by Takanu** [comment] 2022-09-08 05:13
Good to hear!  I'm going to close this now but if you have any other bugs please submit an issue 👌

**Closed as completed by Takanu** 2022-09-08 05:13 UTC
Labels: bug
